# Generated by Django 3.2 on 2021-04-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20210425_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(blank=True, choices=[('High', 'H'), ('Medium', 'M'), ('Low', 'L')], max_length=10, null=True),
        ),
    ]
